# -*- coding: utf-8 -*-
"""numpy_basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1axG9vTgevOz-l-RwVHocwlUQUqC5M18K

Numpy basics
"""

import numpy as np
test = np.array([[1,2,3],[4,5,6]])
print("Test array : ",test)

"""### list vs array in depth

"""

mylist = [1,2,3,4]
myarray = np.array([1,2,3,4])
s1 = mylist*2
s2= myarray*2
print("list squared : ",s1)#doubled
print("array squared : ",s2)#actual square(copy of original)
print(myarray)
s2[2]=10
print(s2,myarray) #copy of original array
s1[2]=10
print(s1,mylist)
for a in range(len(mylist)):#alters the original
  mylist[a]=mylist[a]*2
print("list : ",mylist)
#while in slicing it is oppo
slicedlist=mylist[2:]
slicedarr=myarray[2:]
print("sliced list : ",slicedlist)
print("sliced array : ",slicedarr)
#to check alter na element
slicedarr[1]=10
slicedlist[1]=10
print(slicedarr,myarray,slicedlist,mylist)
#in slicing changes are made to original array
print(s2.base)#view has none
print(myarray.base)
print(slicedarr.base)

"""###Array Attributes (to know numberof elements in diff ways)"""

#ndim,size,shape
a1=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]],dtype=np.int32)
a2=np.array([1,2,3,4])
print(a1.strides)#how mant bits require to step to next row n col
print(a2.strides)#step unless mentioned one == stride
print(a2.strides[0])#one step containshow many bytes
print(a2.dtype)
print(a1.ndim)#dimension - 2
print(a1.shape)#no of rows n cols (3,4)
print(a1.size)#no.of elements
print(a1.base)
for x in a1.flat:
  flat2 = np.append(a1.flat,x)
  print(x)#the real use case of flat to iterate
print(flat2)
flat_a1=a1.flat
print(flat_a1)# the object behind
m1 = a1.flatten()
m2 = a1.ravel()
print("Copy of original by flatten",m1)
print("View of original by ravel",m2)
len(a1.shape)==a1.ndim#to think abt it like how deep one can go with array is len
#base=== an arr is base to another if its a view of that n not the copy or original array

"""### App.1 windows view"""

from numpy.lib.stride_tricks import as_strided
arr = np.array([1,2,3,4,5,6])
ws = int(input("Enter the window size : "))
if(arr.size>=ws) :
  shape = (arr.size - ws + 1,ws)
  stride = arr.strides[0]
  strides = (stride,stride)
  output = as_strided(arr,shape,strides) #array(2D),the shape,how much to jump
  print(output)
else:
  print("Invalid input for ws in order to calculate shape")

"""P1"""

#creating numpy with arange [a,b)
arr=np.arange(1,10)
x=range(1,10)
print(arr)
print(x)
print(list(x))
#arrange is np equivalent of list(range())
#fails when floating value
a=np.linspace(1,10,7,endpoint=True,retstep=True)
#nums equally spaced so (stop - start)/(num - 1)===retstep
print(a)
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])
print(A[:4, :4])

import matplotlib.pyplot as plt
cvalues = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]
c=np.array(cvalues)
print(c)
f=c*9/5+32
print(f)
plt.plot(c)
plt.show()
plt.plot(f)
plt.show()

#to copy arrays
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]],order='F')
B=np.copy(A,order='F')
_=np.dot(A,B)
print(_)
A[1,2]=75
print(A)
print(B)
c=A.copy()
print(c)
print(B.flags["C_CONTIGUOUS"])
print(c.flags["C_CONTIGUOUS"])
#prictal use case
import time
ac = np.random.random((3,3))
bc = np.random.random((3,3))
af=np.copy(ac,order='F')
bf=bc.copy(order="F")
start_a=time.time()
_=np.dot(ac,bc)
print(_.dtype)
print(_)
end_a=time.time()
start_b=time.time()
_=np.dot(af,bf)
print(_)
end_b=time.time()
print(f"Using C order {end_a-start_a}")
print(f"Using F order {end_b-start_b}")
#take aways that different orders have different execution time in fidd functions
#np.copy takes any  datatype while arr.copy cant dot is always userd incol order

#itendity array
a=np.identity(3,dtype='int')
print(a)
b=np.eye(4,3,k=1,dtype="int")
print(b)
#practical use case for thomas algo or tridiagonal algo and for ax=b
#for a
n=5
l=1
h=l/(n+1)
main_d=-(2-h**2)*np.eye(n,dtype='int')
#print(main_d)
right_d=np.eye(n,k=1,dtype='int')
#print(right_d)
left_d=np.eye(n,k=-1,dtype='int')
#print(left_d)
a=main_d+right_d+left_d
print(a)
a_copy=a.copy()#copying just before changes
#for x
x0=0
xn=1

#for b
b=np.zeros(n,dtype='int')
b[0]-=x0
b[n-1]-=xn
print(b)

#back to x
x_middle = np.linalg.solve(a_copy, b)#solution to the interior values of x
print(x_middle)
x_full=np.concatenate(([x0],x_middle,[xn]))
print(x_full)
print("\nModified A (after BCs applied to b):\n", a)
print("\nRight-hand side vector b:\n", b)
print("\nSolution including boundaries:\n", x_full)

#playing with dtype
#np array with different dtype in it
d = np.dtype(np.int16)
print(d)
a= np.array([(1,2),(3,4)],dtype=d)
b=np.array([[1,2],[1,2]],dtype=d)
print(b)
print(a)
lst = [ [3.4, 8.7, 9.9],
[1.1, -7.8, -0.7],
[4.1, 12.3, 4.8] ]
B = np.array(lst)
print(B)
A = np.array(lst, dtype=d)
print(A)#floor value
# till now we have seen that dtype can convert an input list or tuples into disaired datatype which is normal usecase
#structured dtype
dt =np.dtype([("density",np.int32)])
print(dt)
arr=np.array([12,23,445],dtype=dt)
print(arr)
print(repr(arr))
td=np.dtype([('country',np.str_,20),('density','i4'),('area','i4'),('population','i4')])
population_table = np.array([
('Netherlands', 393, 41526, 16928800),
('Belgium', 337, 30510, 11007020),
(11, 256.824, 243610, 62262000)],dtype=td)
print(population_table)

#csv example
np.savetxt("file.csv",
           population_table,
           fmt="%s,%d,%d,%d",
           delimiter=',',#columns seperator
          )#write to a file
x=np.genfromtxt("file.csv",
                dtype=td,
                delimiter=',')#ignores the heading
print(x)#read from file

#creating a csv file
data = [
    [1, 0.98, 42, 22, 12],
    [2, 1.02, 44, 53, 66],
    [3, 1.01, 50, 60, 70]
]
np.savetxt("data.csv",
           data,
           header="senser,configure,r1,r2,r3",
           delimiter=",",
           fmt="%s"
          )
#store it in np array
dt=np.dtype([("sensors","i4"),("configure","f4"),("records",("i4",3))])
x=np.genfromtxt(
                "data.csv",
                dtype=dt,
                delimiter=","
              )
a=np.array(x)
print(a)
mult_array=a['records']*a['configure'][:,None]#broadcasting

#mult_array = np.zeros_like(a['records'], dtype=np.float32)
for i in range(len(a)):
  c=int(a['sensors'][i])
  for j in range(len(a['records'][i])):
   mult_array[i,j]=a['configure'][i]*a['records'][i][j]


print(mult_array)
i_o=np.eye(N=c,dtype='int')
print(i_o)
i_c=np.copy(i_o)
#i_c[2][2]=4
#print(i_c)
#print(i_o)
print(f"Modified : \n{2*i_c}")
#transform to csv
np.savetxt(
    "configure.csv",
    comment='',
    mult_array
)
#optimization mult_array and c

"""### Broadcasting basics n dot product"""

#dot product
#on 2d
a = np.array([[1, 2,3], [3, 4,5]])
#b = np.array([[5, 6], [7, 8]])
#r=np.zeros((2,2), dtype=np.int64)#same dimensions and order dtpe n all
#np.dot(a,b,out=r)#out==output stored in which array
#print(r)
#print(a[-1])
#print(b[-2])
#use -1 for last
#broadcasting
bb =np.array([1,2,3])
#without
ba=bb[np.newaxis,:]#adds a new dim/axis here row wise
print(ba.ndim)
b1=np.concatenate([ba,ba])#only integer can be concatenate so wrap in listor tuple
#row wise concatenate
print(b1)
print("mult using add axis n add row : ",a*b1)
#tile
B = np.tile(np.array([1, 2, 3]),(2,1))
print(B)
print("mult using tile : ",a*B)
#broadcasting
print('mult using broadcasting : ',a*bb)
#distance matrix
city = ["Barcelona", "Berlin", "Brussels", "Bucharest"]
dist2barcelona = [0, 1498, 1063, 1968]
d=np.array(dist2barcelona)
dd=np.abs(d-d[:,np.newaxis])
print(d)
print(dd)

#broadcasting practical example
x =np.array([[1,2,3],
    [4,5,6],
    ]
    )
r,c=np.shape(x)
print("shape of x :",x.shape)
y=np.array([1,3])
w=np.array([0.1,0.2,0.3])
print("shape of y :",y.shape)
print("shape of w :",w.shape)
y_pred = x@w
y_pred_dot=np.dot(x,w)
print(y_pred,y_pred_dot)
print("shape of y_pred :",y_pred.shape)
err=y_pred-y
print(err)
print(x.T)
print("shape of err :",err.shape)
grad=(x.T@err)/r
gc=np.copy(grad)
print(grad)
im=np.identity(c)
print('identity matrix : ',im)
print("shape of im :",im.shape)
print("shape of grad :",grad.shape)
dt=np.dtype([("grad",np.float32),("w",np.float32)])
d=np.array([grad,w],dtype=dt)
print(im)
print(d)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.concatenate((a,b)))#contatenate of the same size
print(np.concatenate((a,b),axis=1))

