# -*- coding: utf-8 -*-
"""pytorch_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AnpPVtYG4t-fqbntwAjDen0Vo2fPKCBH

Learning Pytorch
"""

import torch
import numpy as np

#working with tensor
#make tensor from a data
data=[[2,3],[1,3],[4,5],[6,7]]
x_data=torch.tensor(data)
print(x_data,x_data.shape,x_data.dtype,x_data.device)#attributes of tensor
x_para=torch.tensor(data,dtype=torch.float32)
print(x_para)
x_para=x_para.reshape(2,4)
print(x_para)

#make tensor from_numpy or like
num_arr=np.array([[[1,2]],[[3,4]]])
x_np=torch.from_numpy(num_arr)
x_ones_like=torch.ones_like(x_data)
x_randn_like=torch.randn_like(x_data, dtype=torch.float)
x_rand_like=torch.randint_like(x_data, low=0, high=11) # Added low and high arguments
print(x_np,x_ones_like,x_randn_like,x_rand_like)
#just _like requires input to be in float so pass a parameter while randint requires a lower value(inclusive) and higher limit (non inclusive)

#make tensor from standard 9 types
shape=(2,3)
rand=torch.rand(shape)
randn=torch.randn(4)
empty=torch.empty(shape)
zeros=torch.zeros(shape)
linspace=torch.linspace(0,10,5)
print(rand,randn,empty,zeros,linspace)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,7))
plt.plot(rand.numpy(),label="rand.tensor",color='blue')
plt.plot(randn.numpy(),label="randn.tensor",color='red')
plt.plot(zeros.numpy(),label="zeros.tensor",color='green')
plt.plot(empty.numpy(),label="empty.tensor",color='purple',linestyle="--")
plt.plot(linspace.numpy(),label="linspace.tensor",color='pink')

plt.figure(figsize=(12, 6))

plt.plot(rand.numpy(), label="torch.rand", color="blue", alpha=0.7)
plt.plot(randn.numpy(), label="torch.randn", color="red", alpha=0.7)
plt.plot(zeros.numpy(), label="torch.zeros", color="black", linewidth=2)
plt.plot(linspace.numpy(), label="torch.linspace", color="hotpink", linewidth=2.5)

# Optional: Adding legend so you can identify the clean lines
plt.legend()
plt.title("Correctly Aligned PyTorch Tensors")
plt.grid(True, linestyle=":", alpha=0.6)

plt.show()

#few operations
#slicing
data=[[2,3],[1,3],[4,5],[6,7]]
x_para=torch.tensor(data,dtype=torch.float32)
x_para=x_para.reshape(2,4)
print(x_para)
print(x_para[0,0])
print(x_para[:,3])
print(x_para[1,:])
x_para[1,:]=3
print(x_para)

#dim reduction
#dim=0 operations on every col | check every column so column wise and recturn row index , dim=1 op on every row = check row wise return column index
data=[[2,3],[1,3],[4,5],[6,7]]
x_para=torch.tensor(data,dtype=torch.float32)
x_para=x_para.reshape(2,4)
print(x_para)
x_in=torch.argmax(x_para,dim=1)#return index in a tensor if dim =1 returns col index otherwise dim=0 row index
print(x_in)#tensor
row_in=torch.arange(x_para.size(0))#size -2 to 1 0:rows 1:col
print(row_in)
print(x_para[row_in,x_in])
col_in=torch.arange(x_para.size(1))
print(col_in)
x_in2=torch.argmax(x_para,dim=0)
print(x_in2)
print(x_para[x_in2,col_in])


#using max
max_values, max_indices = torch.max(x_para, dim=1)
print(max_values)
print(max_indices)

#torch.gather contomise
data=[[2,3],[1,3],[4,5],[6,7]]
x_para=torch.tensor(data,dtype=torch.float32)
print(x_para)
tem1=torch.tensor([[0],[1],[0],[1]])
print(tem1)
r1=torch.gather(x_para,dim=0,index=tem1)#go row wise check cols of tem1
print(r1)

