# -*- coding: utf-8 -*-
"""sql_alchemy_learn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MciVT2WdVCi_K_DFE7ikuRlbR6hTisLz

Basic with osm layer
"""

import sqlalchemy as sa
engine=sa.create_engine("sqlite:///:memory:")#temp db in ram not works for postgresql
connection=engine.connect()
metadata=sa.MetaData()
print(engine,connection,metadata)

#question paper info
#functional method only
q_p_table=sa.Table(
    "question_paper",#table name
    metadata,#store in metadata?
    sa.Column("uuid",sa.Integer(),primary_key=True),
    sa.Column("paper_name",sa.String(),default=None)
)

print(q_p_table)
print(metadata)

def insert_table(id:int,name:str)->None:
  query=q_p_table.insert().values(uuid=id,paper_name=name)
  connection.execute(query)

def select_user(name:str)->sa.engine.Result:
  query = q_p_table.select().where(q_p_table.c.paper_name==name)
  result = connection.execute(query)
  return result.fetchone()

def main():
  metadata.create_all(engine)
   # Changed uuid from 2 to 3 to avoid UNIQUE constraint violation
  print(select_user("jxasijixsa"))

if __name__=="__main__":
  main()

"""with classes"""

from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase,sessionmaker
engine=create_engine(
    "sqlite:///:memory:",
    pool_pre_ping=True#sends a ping message that are you awake to db
)
class Base(DeclarativeBase):#orm layer
  pass
session=sessionmaker(engine)

from sqlalchemy import Column,Integer,String,select
class Qpaper(Base):
  __tablename__="questpaper"
  uuid=Column(Integer,primary_key=True)
  subject=Column(String,default="practice")
   # Added this so it prints nicely instead of a raw memory address
  def __repr__(self) -> str:
      return f"Qpaper(uuid={self.uuid}, subject='{self.subject}')"
def main():
  #metadata awake
  Base.metadata.create_all(engine)
  #methods of class
  q1=Qpaper(uuid=1,subject="maths")
  q2=Qpaper(uuid=3)
  #give the info of class to session
  with session() as s:
    #add and commit insert into values
    s.add_all([q1,q2])
    s.commit()
    #make a query select * form table
    query=select(Qpaper)
    #execute
    result=s.execute(query)
    print(result)
    #fetchone in orm
    all_papers = result.scalars().all()
    print(all_papers)
if __name__=="__main__":
  pass

