# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VbpMSvV4ZXPKbh96-CC0ejiecr50VvPw
"""

# premkt_dashboard.py
import requests, json, time, datetime
import pandas as pd
from bs4 import BeautifulSoup

# Google Sheets libs
import gspread
from google.oauth2.service_account import Credentials

# ---------- CONFIG ----------
SHEET_NAME = "Your Google Sheet Name Here"
TAB_NAME = "PreMarket"
BANKNIFTY_SPOT = 50000  # change to current if you want impact calcs (used only for optional columns)

# Google service account JSON path (download from GCP console)
SERVICE_ACCOUNT_FILE = "service_account.json"

# gspread auth
scopes = ["https://www.googleapis.com/auth/spreadsheets",
          "https://www.googleapis.com/auth/drive"]
creds = Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=scopes)
gc = gspread.authorize(creds)
sh = gc.open(SHEET_NAME)
worksheet = sh.worksheet(TAB_NAME)

# helper to write row
def write_row(row_values):
    worksheet.append_row(row_values, value_input_option='USER_ENTERED')

# ---------- DATA FETCHERS ----------
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

def fetch_sgx_nifty_change():
    # Using investing.com public page scraping (fallback)
    try:
        url = "https://www.investing.com/indices/nifty-50-futures"
        r = requests.get(url, headers=HEADERS, timeout=8)
        soup = BeautifulSoup(r.text, "html.parser")
        el = soup.find("span", {"data-test": "instrument-price-change-percent"})
        if el:
            txt = el.text.strip().replace("%", "")
            return float(txt)
    except Exception as e:
        print("sgx fetch err", e)
    return None

def fetch_us_futures_change():
    # grab ES futures change from investing.com (S&P)
    try:
        url = "https://www.investing.com/indices/us-spx-500-futures"
        r = requests.get(url, headers=HEADERS, timeout=8)
        soup = BeautifulSoup(r.text, "html.parser")
        el = soup.find("span", {"data-test": "instrument-price-change-percent"})
        if el:
            txt = el.text.strip().replace("%", "")
            return float(txt)
    except Exception as e:
        print("us futures err", e)
    return None

def fetch_asia_futures_change():
    # simple average of Nikkei and Hang Seng futures change (investing.com pages)
    vals = []
    for url in ["https://www.investing.com/indices/japan-ni225-futures",
                "https://www.investing.com/indices/hang-seng-futures"]:
        try:
            r = requests.get(url, headers=HEADERS, timeout=8)
            soup = BeautifulSoup(r.text, "html.parser")
            el = soup.find("span", {"data-test": "instrument-price-change-percent"})
            if el:
                vals.append(float(el.text.strip().replace("%", "")))
        except:
            continue
    return (sum(vals)/len(vals)) if vals else None

def fetch_india_vix():
    try:
        url = "https://www.nseindia.com/api/option-chain-indices?symbol=NIFTY"
        r = requests.get(url, headers=HEADERS, timeout=8)
        data = r.json()
        # NSE returns list with vix in 'records'->'underlyingValue' not direct; fallback to moneycontrol or scraped value
    except Exception:
        # fallback scrape Moneycontrol
        try:
            r = requests.get("https://www.moneycontrol.com/markets/indian-indices/india-vix-IEV4", headers=HEADERS, timeout=8)
            soup = BeautifulSoup(r.text, "html.parser")
            el = soup.find("div", {"class": "inprice1"})
            if el:
                return float(el.text.strip())
        except:
            pass
    return None

def fetch_banknifty_fut_change():
    # NSE pre-open or futures scraping (may be rate-limited)
    try:
        url = "https://www.nseindia.com/api/market-data-pre-open?key=BANKNIFTY"
        r = requests.get(url, headers=HEADERS, timeout=8)
        data = r.json()
        if "preOpen" in data and "lastPrice" in data["preOpen"]:
            # This endpoint format may vary. Fall back to other.
            return None
    except:
        pass
    # fallback: compute using option chain underlying value if available
    try:
        url = "https://www.nseindia.com/api/option-chain-indices?symbol=BANKNIFTY"
        r = requests.get(url, headers=HEADERS, timeout=8)
        js = r.json()
        if "records" in js and "underlyingValue" in js["records"]:
            spot = js["records"]["underlyingValue"]
            # fetch futures price approx: using 1% assumption or same as spot
            return 0.0  # placeholder
    except:
        pass
    return None

def fetch_fii_dii_cash():
    # Moneycontrol provides FII/DII data; scraping example
    try:
        url = "https://www.moneycontrol.com/stocks/marketstats/marketstats.php?optex=N"
        r = requests.get(url, headers=HEADERS, timeout=8)
        soup = BeautifulSoup(r.text, "html.parser")
        # locate table and parse values
        # For brevity return None if parsing complex
    except:
        pass
    return None

def fetch_option_chain_banknifty():
    # NSE option chain (BankNifty)
    try:
        url = "https://www.nseindia.com/api/option-chain-indices?symbol=BANKNIFTY"
        r = requests.get(url, headers=HEADERS, timeout=8)
        js = r.json()
        return js
    except Exception as e:
        print("option chain err", e)
    return None

def compute_oi_signals(option_js):
    # Simplified OI sign extractor:
    # We look at calls vs puts OI change near ATM strikes in pre-market snapshot.
    if not option_js or "records" not in option_js:
        return ("MIXED","MIXED", "MIXED")
    # crude approximation: sum CE OI change and PE OI change across near strikes
    ce_change = 0
    pe_change = 0
    records = option_js["records"]
    if "data" in records:
        for row in records["data"]:
            ce = row.get("CE")
            pe = row.get("PE")
            if ce and "changeinOpenInterest" in ce:
                ce_change += float(ce["changeinOpenInterest"] or 0)
            if pe and "changeinOpenInterest" in pe:
                pe_change += float(pe["changeinOpenInterest"] or 0)
    ce_sign = ("CE↑" if ce_change>0 else "CE↓" if ce_change<0 else "MIXED")
    pe_sign = ("PE↑" if pe_change>0 else "PE↓" if pe_change<0 else "MIXED")
    # heatmap signal: compare aggregate
    heat = "BULL" if pe_change>ce_change else "BEAR" if ce_change>pe_change else "MIXED"
    return (ce_sign, pe_sign, heat)

def fetch_top5_banks_preopen():
    # Use Yahoo Finance / TradingView data for pre-market quotes
    banks = {
        "HDFCBANK.NS":"HDFCBANK",
        "ICICIBANK.NS":"ICICIBANK",
        "SBIN.NS":"SBIN",
        "AXISBANK.NS":"AXISBANK",
        "KOTAKBANK.NS":"KOTAKBANK"
    }
    vals = {}
    for sym in banks:
        try:
            url = f"https://query1.finance.yahoo.com/v7/finance/quote?symbols={sym}"
            r = requests.get(url, timeout=6, headers=HEADERS)
            js = r.json()
            if "quoteResponse" in js and js["quoteResponse"]["result"]:
                q = js["quoteResponse"]["result"][0]
                prev = q.get("regularMarketPreviousClose")
                price = q.get("regularMarketPrice")
                if price and prev:
                    vals[banks[sym]] = ((price - prev) / prev) * 100
        except:
            vals[banks[sym]] = None
    # compute average of available
    nums = [v for v in vals.values() if v is not None]
    avg = (sum(nums)/len(nums)) if nums else None
    return avg, vals

def fetch_dxy_crude_us_yields():
    # DXY via investing.com or alternative; crude via API; US 10y via finance.yahoo
    dxy = None
    crude = None
    us10 = None
    india10 = None
    try:
        # DXY
        url = "https://query1.finance.yahoo.com/v7/finance/quote?symbols=DXY"
        r = requests.get(url, timeout=6, headers=HEADERS).json()
        if r["quoteResponse"]["result"]:
            dxy = r["quoteResponse"]["result"][0].get("regularMarketChangePercent")
    except:
        pass
    try:
        # crude (CL=F)
        url = "https://query1.finance.yahoo.com/v7/finance/quote?symbols=CL=F"
        r = requests.get(url, timeout=6, headers=HEADERS).json()
        if r["quoteResponse"]["result"]:
            crude = r["quoteResponse"]["result"][0].get("regularMarketChangePercent")
    except:
        pass
    try:
        # US 10y (^TNX in Yahoo is yield*10)
        url = "https://query1.finance.yahoo.com/v7/finance/quote?symbols=^TNX"
        r = requests.get(url, timeout=6, headers=HEADERS).json()
        if r["quoteResponse"]["result"]:
            # ^TNX is yield in percent * 10; convert accordingly or use value direct
            us10 = r["quoteResponse"]["result"][0].get("regularMarketPrice")
    except:
        pass
    try:
        # India 10y from tradingeconomics or yahoo symbol IN10Y? fallback None
        india10 = None
    except:
        pass
    return dxy, crude, us10, india10

# ---------- DECISION / SCORING ----------
def score_signal(val, bull_thresh, bear_thresh):
    """Helper: returns +1 for bull, -1 for bear, 0 for neutral"""
    if val is None:
        return 0
    try:
        v = float(val)
    except:
        return 0
    if v >= bull_thresh:
        return 1
    if v <= bear_thresh:
        return -1
    return 0

def compute_overall_signal(rowdict):
    # rowdict contains keys from fetchers
    score = 0
    # 1. SGX (if +ve strong)
    score += score_signal(rowdict.get("sgx"), 0.25, -0.25)
    # 2. US futures
    score += score_signal(rowdict.get("usfut"), 0.25, -0.25)
    # 3. Asia futures
    score += score_signal(rowdict.get("asiafut"), 0.25, -0.25)
    # 4. VIX (lower is bull)
    vix = rowdict.get("vix")
    if vix:
        if vix < 12: score += 1
        elif vix > 16: score -= 1
    # 5. BankNifty futures % change (if available)
    score += score_signal(rowdict.get("bnfut"), 0.3, -0.3)
    # 6. FII Cash
    if rowdict.get("fii_cash") is not None:
        score += (1 if rowdict["fii_cash"] > 0 else -1)
    # 7. FII futures ratio
    if rowdict.get("fii_ratio") is not None:
        score += (1 if rowdict["fii_ratio"] > 52 else -1 if rowdict["fii_ratio"] < 48 else 0)
    # 8. PCR (lower bullish)
    pcr = rowdict.get("pcr")
    if pcr:
        score += (1 if pcr < 0.9 else -1 if pcr > 1.1 else 0)
    # 9. Max pain: if spot > maxpain => bull else bear (if maxpain exists)
    maxpain = rowdict.get("maxpain")
    spot = rowdict.get("spot")
    if maxpain is not None and spot is not None:
        score += (1 if spot > maxpain else -1)
    # 10. OI CE/PE signs
    ce_sign = rowdict.get("ce_sign")
    pe_sign = rowdict.get("pe_sign")
    if pe_sign == "PE↑": score += 1
    if ce_sign == "CE↑": score -= 1
    # 11. Heatmap
    heat = rowdict.get("heat")
    if heat == "BULL": score += 1
    if heat == "BEAR": score -= 1
    # 12. Top5Banks avg
    top5 = rowdict.get("top5_avg")
    if top5 is not None:
        score += score_signal(top5, 0.25, -0.25) * 2  # give higher weight
    # 13. DXY
    score += score_signal(rowdict.get("dxy"), -0.1, 0.1) * -1  # DXY up = bad
    # 14. Crude
    score += score_signal(rowdict.get("crude"), -0.2, 0.2) * -1
    # 15-16 yields - already included via dxy/us10 etc (skip)
    # 17. Volume spikes (count)
    vs = rowdict.get("vol_spikes")
    if vs and vs >= 2:
        score += 1 if rowdict.get("top5_avg",0) > 0 else -1
    # 18. Gap
    if rowdict.get("gap") == "GAP_UP":
        score += 1
    elif rowdict.get("gap") == "GAP_DOWN":
        score -= 1
    # 19. Block deals
    if rowdict.get("block_signal") == "BUY":
        score += 1
    elif rowdict.get("block_signal") == "SELL":
        score -= 1
    # 20. Major news flag
    if rowdict.get("news_flag") == "POS":
        score += 1
    elif rowdict.get("news_flag") == "NEG":
        score -= 1

    return score

# ---------- MAIN ----------
def build_premarket_row():
    row = {}
    row['timestamp'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    row['sgx'] = fetch_sgx_nifty_change()
    row['usfut'] = fetch_us_futures_change()
    row['asiafut'] = fetch_asia_futures_change()
    row['vix'] = fetch_india_vix()
    row['bnfut'] = fetch_banknifty_fut_change()
    row['option_chain'] = fetch_option_chain_banknifty()
    ce_sign, pe_sign, heat = compute_oi_signals(row['option_chain'])
    row['ce_sign'] = ce_sign
    row['pe_sign'] = pe_sign
    row['heat'] = heat
    top5_avg, top5_vals = fetch_top5_banks_preopen()
    row['top5_avg'] = top5_avg
    row['top5_vals'] = json.dumps(top5_vals)
    dxy, crude, us10, india10 = fetch_dxy_crude_us_yields()
    row['dxy'] = dxy
    row['crude'] = crude
    row['us10'] = us10
    row['india10'] = india10
    # placeholders for data points that require custom parsing or paid APIs
    row['fii_cash'] = None
    row['fii_ratio'] = None
    row['pcr'] = None
    row['maxpain'] = None
    row['spot'] = None
    row['vol_spikes'] = None
    row['gap'] = "NO_GAP"
    row['block_signal'] = None
    row['news_flag'] = None

    score = compute_overall_signal(row)
    row['score'] = score
    if score >= 6:
        row['final'] = "Bullish"
    elif score <= -6:
        row['final'] = "Bearish"
    else:
        row['final'] = "Neutral"

    return row

def row_to_sheet_values(r):
    vals = [
        r['timestamp'],
        r['sgx'],
        r['usfut'],
        r['asiafut'],
        r['vix'],
        r['bnfut'],
        r['fii_cash'],
        r['fii_ratio'],
        r['pcr'],
        r['maxpain'],
        r['ce_sign'],
        r['pe_sign'],
        r['heat'],
        r['top5_avg'],
        r['dxy'],
        r['crude'],
        r['us10'],
        r['india10'],
        r['spot'],
        r['vol_spikes'],
        r['gap'],
        r['block_signal'],
        r['news_flag'],
        r['score'],
        r['final']
    ]
    return vals

if __name__ == "__main__":
    row = build_premarket_row()
    vals = row_to_sheet_values(row)
    write_row(vals)
    print("Done. Final signal:", row['final'])