# -*- coding: utf-8 -*-
"""stocke_s1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q-76BD_OLVgQO__YBOd5ufwjyzWfKeIW
"""

import pandas as pd
import yfinance as yf
import time as time
from google.colab import files
uploaded = files.upload()

import pandas as pd
import yfinance as yf
import time

# Read the CSV
companies = pd.read_csv("ind_nifty50list.csv")

# Lists to hold fetched info
sectors = []
price = []
market_cap = []
volumes = []

for sym in companies["Symbol"]:
    print("Fetching:", sym)
    yf_sym = sym + ".NS"
    try:
        ticker = yf.Ticker(yf_sym)
        info = ticker.info

        sector = info.get("sector") or info.get("industry") or "Unknown"
        sectors.append(sector)
        price.append(info.get("regularMarketPrice"))
        market_cap.append(info.get("marketCap"))
        volumes.append(info.get("regularMarketVolume"))
    except Exception as e:
        print(f"Error fetching {sym}: {e}")
        sectors.append("Unknown")
        price.append(None)
        market_cap.append(None)
        volumes.append(None)

    time.sleep(0.1)

# Add fetched info to dataframe
companies["sector"] = sectors
companies["price"] = price
companies["market_cap"] = market_cap
companies["volume"] = volumes

# Sort by sector first
companies_sorted = companies.sort_values(by="sector")  # optional: by industry within sector

# Write to Excel
companies_sorted.to_excel("nifty50_by_sector_sorted.xlsx", index=False)
print("Excel created: nifty50_by_sector_sorted.xlsx")

import os
os.listdir()
from google.colab import files
files.download("nifty50_by_sector_sorted.xlsx")